### PR TITLE
Update Pure.DI to 2.0.0

### PR DESCRIPTION
**Pull request by NikolayPianikov**

### CODE REVIEW

**Comment by NikolayPianikov** [comment]
Requires [.NET SDK 6.0.4xx or newer](https://dotnet.microsoft.com/download/dotnet/6.0)

**Comment by NikolayPianikov** [comment]
@danielpalme when you have time, please take a look at my MR

**Comment by danielpalme** [comment]
Your code does not compile on my machine.
`ContainerAdapterBase.Resolve(Type)` is no longer implemented by PureDiAdapter.

I don't think it makes any sense to put further effort into this benchmark.
It's outdated and has to be rewritten for .NET Core.

**Comment by NikolayPianikov** [comment]
@danielpalme The code may not compile because dotnet build services have downloaded and are using an older version of the code generator.
You can delete the _bin_ and _obj_ folders in the project and then run the following commands in sequence:
```
dotnet build-server shutdown
dotnet restore
dotnet build
```

As for moving to .NET Core, I can offer help.
[Here](https://github.com/DevTeam/Pure.DI/tree/master/benchmarks/Pure.DI.Benchmarks) I have a project similar to yours. It measures several scenarios using different libraries and uses the [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) library to measure performance. It does the library pretty well, and you can also measure how much memory is being wasted.

**Comment by NikolayPianikov** [comment]
And separately we can add functionality that will check if the libraries work correctly in different scenarios without messing up performance statistics.

**Comment by danielpalme** [comment]
I was able to build the project. I updated the benchmark one last time. The project will now be archived.

I don't have the time to start the project in .NET Core. But your project is a good start!

**Pull request merged**
