### PR TITLE
Ensure root services are resolve prior to running benchmarks

### PR DESCRIPTION
**Pull request by seesharper**
There is still a minor problem related to the fact that containers with less features has less root services, but I don't think we need to adjust for that at the moment as most of the top performing containers implements basically all features.

### CODE REVIEW

**Comment by ipjohnson** [comment]
Out of curiosity what did the before and after numbers look like?

**Comment by seesharper** [comment]
I did not compare the result before and after, but my guess is that AVL tree based lookup will actually suffer  from this as the trees or subtrees gets deeper. I have noticed that we (LightInject, Grace and DryIoc) basically have the same tree implementation. Will be interesting to see the results though :)

**Comment by ipjohnson** [comment]
Cool, I agree it will probably have some effect because at some point dictionary<,> will be faster. Like everything it really depends on your use case.

**Comment by dotnetjunkie** [comment]
Those tree implementations are O(log n), but it takes to somewhere between a 1000 and 2000 registrations before the normal dictionary implementation starts to outperform this particular tree implementation.

**Comment by seesharper** [comment]
@ipjohnson  btw, congrats on those numbers. Man, you are fast 👍

**Comment by ipjohnson** [comment]
Thanks at this point all the top containers are so fast it's hard to go

**Comment by dotnetjunkie** [comment]
I agree with @seesharper , @ipjohnson 's perf results are insane.

**Pull request merged**
