### PR TITLE
- added measurement of prepare times

### PR DESCRIPTION
**Pull request by asd-and-Rizzo**
- added possibility to be fair about basic features
- made Dispose safe
- added documentation

### CODE REVIEW

**Comment by danielpalme** [comment]
One question:
I don't understand why not all containers support your new benchmark.
Can you explain that?

**Comment by asd-and-Rizzo** [comment]
will fix this. this commit just tested that there are real diffs and test is good. also design of test is logical. but akin to some hack, so i thought of some comment which will need refactoring so doing all containers could be work to redo again.ì

**Comment by danielpalme** [comment]
I have to fix one or two issues before I can commit your pull request.
Will take a few days.

**Comment by danielpalme** [comment]
Merged into new branch. Still some open TODOs:
9edffb77e063b72ecd3837dbfafe38a57e9cb22a

**Comment by danielpalme** [comment]
Finally merged into "master."

**Pull request closed without merging**
