### PR TITLE
updating asp.net core benchmark to have more scoped singletons

### PR DESCRIPTION
**Pull request by ipjohnson**
This PR is to address concerns brought up in issue #115. I've made the test have 5 scoped singletons and changed the read:create ratio from 3:1 to 5:1 to make it more read heavy as specified in the issue.

### CODE REVIEW

**Comment by jzabroski** [comment]
@ipjohnson Something I've been thinking/wondering - wouldn't the benchmarks be better if there was a "Hugeness multiplier" so that people could pick a IoC container based on size of project?  Like, I worked on a project with a lot of pseudo-cyclical references and so object graphs were routinely 30 objects deep.  It's these types of benchmarks where we felt DryIoC shined.

**Comment by ipjohnson** [comment]
@jzabroski that could be interesting to people. That said this PR is specifically to address @barsonax concern that a particular container was “cheesing” the benchmark.

That said if you’d like to add a really large object to these I’m sure it would be welcome.

**Comment by Barsonax** [comment]
Nice job

I still think most of the time in the benchmark goes into creating the scoped instances and not actually resolving them.

What about using only 1 scope and resolve 3 controllers in that scope? I believe that should make for a nice 15:1 read write ratio while reducing the constant overhead of creating the scopes.

**Comment by dadhi** [comment]
@Barsonax , Hmm.. I have thought that it always one scope per controller.

**Comment by Barsonax** [comment]
Hmm you might be right here. Seems that in ASP .NET a new controller is created for every request. Since the scope here is the request scope there will only be 1 controller in a scope I believe.

Maybe a linkedlist might actually be a better datastructure for this particular workload due it being fast to add new instances.

**Comment by ipjohnson** [comment]
@jzabroski good question maybe best posed in a new issue so all stake holders can express their interest. I think you could probably come up with 100+ benchmarks that are interesting to some segment of DI users that aren't covered here.

**Comment by ipjohnson** [comment]
@jzabroski good question, probably best posed in a new issue so all the stake holders can be involved in the discussions.

**Comment by ipjohnson** [comment]
Does anyone have comments on this PR before @danielpalme merges it in?

**Comment by jzabroski** [comment]
> @jzabroski good question maybe best posed in a new issue so all stake holders can express their interest. I think you could probably come up with 100+ benchmarks that are interesting to some segment of DI users that aren't covered here.

Created #118

**Pull request merged**
