### PR TITLE
Add MicroResolver library

### PR DESCRIPTION
**Pull request by neuecc**
Hi Daniel, thank you to create great benchmark.
I've created new library called MicroResolver - https://github.com/neuecc/MicroResolver
Your benchmark was very useful for performance tuning and my library marked fastest in some tests -> [result run on my machine(not include this pull request)](https://gist.github.com/neuecc/edc9daa035f3878d0eb0a31d9f76ed24)

This pull request has two area of changes.

* Add MicroResolver
* Changed `object IContainerAdapter.Resolve(Type)` -> `T IContainerAdapter.Resolve<T>()`

There is an arbitrary reason why I changed to `Resolve<T>`.
MicroResolver is optimized for generic method. https://github.com/neuecc/MicroResolver#perforamnce-technique---generic-type-caching-per-resolver
With this change, it is to be used.

If you do not want to do so, revert the changes made by `Resolve<T>` and only add `MicroResolver`.

### CODE REVIEW

**Comment by ipjohnson** [comment]
The change to use Resolve(Type) was made 4 years ago as the generic version is not as common or useful as the non generic implementation. If you look at the history of the files it can be found [here](https://github.com/danielpalme/IocPerformance/commit/eaa811844f51c207bca46acf89bd23a64fb03d52)

From my perspective changing all tests and all containers to uses a generic version just so one container that happens to have optimized for this one scenario can run faster seems way over the top but maybe that's just me.

**Comment by dadhi** [comment]
Agree with @ipjohnson, you obey to the benchmark and not vice versa :-)

**Comment by danielpalme** [comment]
I have added your container to the benchmark. But I agree with @dadhi and @ipjohnson and did not change the Resolve method.

**Comment by neuecc** [comment]
Thank you very much, I also agree with the reason.
Of course, it is important to fight on the same ring.

**Pull request closed without merging**
