### PR TITLE
Add vs-mef adapter

### LINKED ISSUE #120: Add VS-Mef
Should be fairly easy to add?

https://github.com/Microsoft/vs-mef

### PR DESCRIPTION
**Pull request by AArnott**
Closes #120

### CODE REVIEW

**Comment by danielpalme** [comment]
Thanks. Will merge tomorrow.

**Comment by danielpalme** [comment]
Version 16.3.4-alpha seems not to be published on Nuget.
Where can I find it?

**Comment by AArnott** [comment]
You can see the feed in the nuget.config file that I added to your repo.
The web UI for it is [here](https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vssdk&package=Microsoft.VisualStudio.Composition&protocolType=NuGet&version=16.3.4-alpha).

**Comment by AArnott** [comment]
Once it's pushed to nuget.org we can remove the nuget.config file entry. But I would recommend you keep the nuget.config file as every repo should declare its dependencies.

**Comment by danielpalme** [comment]
Thanks. Visual Studio did not recognize the file. I had to reload the solution to solve this.

**Comment by AArnott** [comment]
> I had to reload the solution to solve this.

Quite right. Consider voting up this issue: https://github.com/NuGet/Home/issues/1538

**Comment by danielpalme** [comment]
Does the benchmark work on your machine?

I get an exception on this benchmark:
https://github.com/danielpalme/IocPerformance/blob/0f79d8c00c71ac1696373755465f47b9372f00b1/IocPerformance/Benchmarks/Advanced/06_Generics_Benchmark.cs#L15

System.InvalidOperationException  The sequence contains no elements

Stacktrace:
```
IocPerformance.exe!IocPerformance.Adapters.VSMefContainerAdapter.Resolve(System.Type type) Line 36	C#
IocPerformance.exe!IocPerformance.Benchmarks.Advanced.Generics_06_Benchmark.MethodToBenchmark(IocPerformance.Adapters.IContainerAdapter container) Line 15	C#
IocPerformance.exe!IocPerformance.Benchmarks.Benchmark.Warmup(IocPerformance.Adapters.IContainerAdapter container) Line 43	C#
IocPerformance.exe!IocPerformance.ContainerAdapterRuntime.Run(System.Type containerType, System.Collections.Generic.List<IocPerformance.Benchmarks.BenchmarkResult> existingBenchmarkResults) Line 40	C#
[External Code]	
IocPerformance.exe!IocPerformance.Program.Main(string[] args) Line 44	C#
```

**Comment by AArnott** [comment]
I haven't actually run it completely (it takes a while to execute). So I'll check and fix issues.

**Comment by danielpalme** [comment]
Should fail pretty fast. The `Warmup` method executes every benchmark once before starting the "real" test.

**Comment by danielpalme** [comment]
I merged your PR with `SupportGeneric => false`

**Pull request merged**
