### PR TITLE
adding asp.net core test

### PR DESCRIPTION
**Pull request by ipjohnson**
PR for issue #66

### CODE REVIEW

**Comment by ipjohnson** [comment]
Rough numbers can be found [Here](https://github.com/ipjohnson/IocPerformance)

**Comment by danielpalme** [comment]
@ipjohnson:
Thanks for the PR.
You updated Autofac and Castle Windor. The problem is, that "Castle.Windsor.3.4.0" is not working with "Castle.Core.4.0.0"...
Currently this container benchmark can no longer be executed.
I did not update Autofac an Castle.Windor for some time now, to keep them both working.
But Autofac needs to be updated in order to support asp.net core.

**Comment by ipjohnson** [comment]
I had seen that but I jut figured I'd done something wrong.

I found this [issue](castleproject/Windsor/issues/161) but it doesn't seem to suggest any way to work around it. @jonorossi any suggestions?

Maybe it's a matter of removing Windsor from the benchmark for the moment but publish the 3.3.0 results till 4.0.0 is released? Holding back Autofac from being upgraded because Castle.Windsor is incompatible with Castle.Core 4.0.0 seems wrong.

**Comment by jonorossi** [comment]
> The problem is, that "Castle.Windsor.3.4.0" is not working with "Castle.Core.4.0.0"...

They are not compatible, Windsor 3.4.0's dependencies state: `Castle.Core (>= 3.3.0 && < 4.0.0)`.

Windsor does not yet support .NET Core/Standard, while Castle Core (including Castle DynamicProxy) does. There is currently no workaround for using Windsor 3.x.x with Castle Core 4.0.0 as there were some breaking changes. There is work underway on Windsor 4.0, so it is your call how you want to handle this until then, we need to make a minor Windsor release soon so we could see how much work it would be to support Castle Core 4.0.0 until Windsor 4.0 comes.

**Comment by danielpalme** [comment]
I would suggest, we let the Castle.Windsor tests fail until the new release is available.

**Pull request merged**
