### PR TITLE
Remove MicroResolver

### PR DESCRIPTION
**Pull request by MinhThienDX**
Hello, I tried to remove MicroResolver.
Smoke test ran fine after that.

### CODE REVIEW

**Comment by ipjohnson** [comment]
@neuecc not sure if you saw this. Do you want micro resolver removed from the benchmark?

**Comment by neuecc** [comment]
what reason?
If it works, I think it will be useful as a performance test baseline for those who create new IoC containers.
However, it has certainly not been updated and will not be updated in the future.

**Comment by MinhThienDX** [comment]
`However, it has certainly not been updated and will not be updated in the future.`
I removed it because that reason.
However, danielpalme can close this PR without merging if he want to keep MicroResolver.

**Comment by jzabroski** [comment]
It might be helpful to add a section in the benchmarks for libraries that have previously been benchmarked and were removed either because they stopped being updated or didn't support .NET Core or didn't support Microsoft DI.

**Pull request closed without merging**
